name: Mirror changes to second repo

on:
  push:
    branches:
      - main  # or the branch you use

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout first repo
        uses: actions/checkout@v3

      - name: Push to second repo
        env:
          SECOND_REPO: https://<TOKEN>@github.com/aanjalii01/leetcode.git
        run: |
          git remote add second $SECOND_REPO
          git push second main --force
