name: Sync to Second Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push code to second repo
        env:
          SECOND_GITHUB_TOKEN: ${{ secrets.SECOND_GITHUB_TOKEN }}
        run: |
          git remote add second https://aanjalii01:${SECOND_GITHUB_TOKEN}@github.com/aanjalii01/leetcode.git
          git push second main --force
